# -*- coding: utf-8 -*-
"""02-first-tf-models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WaBwkXEzjl5kg7b87_kYfamyP2G_ov9t
"""

"""
We're going to build our first full fledged Neural Networks with Tensorflow and
Keras

Regression
Predict House Price
  1. Square Footage
  2. number of bedrooms
  3. home age

Classification
Predicting whether a customer will churn (cancel)
  1. monthly bill
  2. support tickets
  3. months as a customer
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

np.random.seed(42)
tf.random.set_seed(42)

print("Setup complete")

# Let's start with our housing example and build our data

n_samples = 400

square_feet = np.random.randint(800, 3500, size=n_samples)
bedrooms = np.random.randint(1, 6, size=n_samples)
home_age = np.random.randint(0, 80, size=n_samples)
"""
our goal is to make real-ish data, larger homes tend to cost more, usually
more bedrooms is the same and older homes typically cost a little less

add some noise to vary the data a little
"""

noise = np.random.normal(0, 25000, size = n_samples)

# 400 realish samples
price = (
    50000
    + square_feet * 180
    + bedrooms * 15000
    - home_age * 1200
    + noise
)

# Let's make a dataframe for this for visualization
housing_df = pd.DataFrame({
    "square_feet": square_feet,
    "bedrooms": bedrooms,
    "home_age": home_age,
    "price": price
})

housing_df.head()

# Quick look at the data itself

print(housing_df.describe())

plt.figure(figsize=(7,4))
plt.scatter(housing_df["square_feet"], housing_df["price"])
plt.xlabel("Square Feet")
plt.ylabel("Price")
plt.title("Home Price vs Square Feet")
plt.show()

plt.figure(figsize=(7,4))
plt.scatter(housing_df["home_age"], housing_df["price"])
plt.xlabel("Home age")
plt.ylabel("Price")
plt.title("Home Price vs Home Age")
plt.show()

# Before we create our model, one final step in preprocessing and that's splitting our data

X_regression = housing_df[["square_feet", "bedrooms", "home_age"]].values
y_regression = housing_df["price"].values

# Split into train and test data
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_regression,
    y_regression,
    test_size=.2,
    random_state=42
)

"""
We need to scale our data
Typically Neural networks perform better when the data is scaled down
This prevents things like one feature (like sq ft) from dominating other feature
(i.e 1800 sq ft vs 2 bedrooms)

There are a couple of different scalers but here we will use the StandardScaler
which returns the Z-Score of the value

Z-Score (don't confuse with weighted sum z) is value - mean / std
"""

regression_scaler = StandardScaler()

# ONLY FIT THE SCALER TO THE TRAIN DATA
# DO NOT FIT THE SCALER TO THE TEST DATA
# We'll need to transform both, but fitting to the test data cause test data
# leakage
# Test data leakage -> Getting a sneak peek at the test data before we're supposed to
X_train_reg_scaled = regression_scaler.fit_transform(X_train_reg)
X_test_reg_scaled = regression_scaler.transform(X_test_reg)

print(X_train_reg[0])
print(X_test_reg_scaled[0])

"""
Let's build a neural network with Keras

Architecture (INITIAL):

3 input features -> Dense Hidden Layer with 2 neurons -> 1 output layer

For regression we do not need sigmoid or softmax
and since we want a linear value, we don't need another activation function in our output layer
"""

# Define the model
# OLD MODEL
# regression_model = tf.keras.Sequential([
#     tf.keras.layers.Input(shape=(3,)), # Input Layer
#     tf.keras.layers.Dense(2, activation='relu'), # Hidden Layer 1
#     tf.keras.layers.Dense(1) # Default function is linear (Output Layer)
# ])

regression_model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(3,)), # Input Layer
    tf.keras.layers.Dense(8, activation='relu'),
    tf.keras.layers.Dense(8, activation='relu'), # Hidden Layer 1
    tf.keras.layers.Dense(4, activation='relu'),
    tf.keras.layers.Dense(1) # Default function is linear (Output Layer)
])

# Compile
regression_model.compile(
    # Optimizer
    # The optimizer tells TF HOW to update the weights
    optimizer=tf.keras.optimizers.Adam(learning_rate=.05),
    # Loss function
    # "Linear" Regression we probably want MSE (Mean Squared Error)
    loss = "mse",
    # Any metrics I want to track
    # Here we'll track absolute error or how far off we are from the actual price
    metrics=["mae"]
)


regression_model.summary()
# Fitting

# Just like scikit learn, after we define the model we need to fit it
regression_history = regression_model.fit(
    X_train_reg_scaled,
    y_train_reg,
    # Epochs is the number of forward passes on all the data
    epochs=100,
    # Validation Split (i.e how much training data should be used for the validation set)
    validation_split=.2,
    verbose=0
)

print("Regression Training Complete")

# Let's look at some metrics and see how we did!
reg_loss, reg_mae = regression_model.evaluate(
    X_test_reg_scaled,
    y_test_reg,
    verbose=0
)

print(f"Test MSE: {reg_loss:,.2f}")
print(f"Test MAE: ${reg_mae:,.2f}")

plt.figure(figsize=(7,4))
plt.plot(regression_history.history["loss"], label="Training Loss")
plt.plot(regression_history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.title("Regression Loss over Time")
plt.legend()
plt.show()

plt.figure(figsize=(7,4))
plt.plot(regression_history.history["mae"], label="Training MAE")
plt.plot(regression_history.history["val_mae"], label="Validation MAE")
plt.xlabel("Epoch")
plt.ylabel("Mean Absolute Error")
plt.title("Regression MAE over Time")
plt.legend()
plt.show()

# Let's make some quick predictions

sample_homes = np.array([
    [1200, 2, 40],
    [2200, 3, 15],
    [3200, 5, 5],
    [1600, 5, 5]
])

# To predict we need to scale and then predict
sample_homes_scaled = regression_scaler.transform(sample_homes)
predicted_prices = regression_model.predict(sample_homes_scaled)

print(predicted_prices)

# Second motivating example:
#
# A company wants to predict whether a customer is likely to cancel.
#
# Features:
#   1. monthly_bill
#   2. support_tickets
#   3. months_as_customer
#
# Target:
#   churned
#       0 = stayed
#       1 = canceled/churned

n_customers = 500

monthly_bill = np.random.normal(85, 25, size=n_customers)
monthly_bill = np.clip(monthly_bill, 30, 180)

support_tickets = np.random.poisson(1.5, size=n_customers)
support_tickets = np.clip(support_tickets, 0, 8)

months_as_customer = np.random.randint(1, 72, size=n_customers)

# Create a probability of churn.
#
# Higher bill -> more likely to churn
# More support tickets -> more likely to churn
# Longer customer history -> less likely to churn

churn_score = (
    -2.0
    + 0.025 * monthly_bill
    + 0.45 * support_tickets
    - 0.035 * months_as_customer
)

churn_probability = 1 / (1 + np.exp(-churn_score))

churned = np.random.binomial(1, churn_probability)

churn_df = pd.DataFrame({
    "monthly_bill": monthly_bill,
    "support_tickets": support_tickets,
    "months_as_customer": months_as_customer,
    "churned": churned
})

churn_df.head()

# Quick Look at the Classification Data


print(churn_df.describe())
print()
print(churn_df["churned"].value_counts())

plt.figure(figsize=(7, 5))
plt.scatter(
    churn_df["monthly_bill"],
    churn_df["support_tickets"],
    c=churn_df["churned"],
    alpha=0.7
)
plt.xlabel("Monthly Bill")
plt.ylabel("Support Tickets")
plt.title("Customer Churn: Monthly Bill vs Support Tickets")
plt.colorbar(label="Churned")
plt.show()

plt.figure(figsize=(7, 5))
plt.scatter(
    churn_df["months_as_customer"],
    churn_df["monthly_bill"],
    c=churn_df["churned"],
    alpha=0.7
)
plt.xlabel("Months as Customer")
plt.ylabel("Monthly Bill")
plt.title("Customer Churn: Customer Age vs Monthly Bill")
plt.colorbar(label="Churned")
plt.show()

# Prepare Classification Features and Target

X_classification = churn_df[[
    "monthly_bill",
    "support_tickets",
    "months_as_customer"
]].values

y_classification = churn_df["churned"].values

X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(
    X_classification,
    y_classification,
    test_size=0.2,
    random_state=42,
    stratify=y_classification
)

classification_scaler = StandardScaler()

X_train_clf_scaled = classification_scaler.fit_transform(X_train_clf)
X_test_clf_scaled = classification_scaler.transform(X_test_clf)

print("Original first training row:", X_train_clf[0])
print("Scaled first training row:", X_train_clf_scaled[0])

# Architecture:
#
#   3 input features
#        ↓
#   Dense hidden layer with 8 neurons
#        ↓
#   Dense hidden layer with 8 neurons
#        ↓
#   Dense hidden layer with 4 neurons
#        ↓
#   1 output neuron
#
# For binary classification, the output layer uses sigmoid.
#
# Sigmoid squishes the output between 0 and 1.
# We can interpret this as a probability-like score.


# FIX THIS IT'S REALLY OVERFIT
classification_model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(3,)),
    tf.keras.layers.Dense(8, activation="relu"),
    tf.keras.layers.Dense(8, activation="relu"),
    tf.keras.layers.Dense(4, activation="relu"),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

classification_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

classification_model.summary()

# Train the Classification Model

classification_history = classification_model.fit(
    X_train_clf_scaled,
    y_train_clf,
    epochs=100,
    validation_split=0.2,
    verbose=0
)

print("Classification training complete.")

# Evaluate the Classification Model

clf_loss, clf_accuracy = classification_model.evaluate(
    X_test_clf_scaled,
    y_test_clf,
    verbose=0
)

print(f"Test Loss: {clf_loss:.4f}")
print(f"Test Accuracy: {clf_accuracy:.4f}")

# Plot Classification Training History

plt.figure(figsize=(7, 5))
plt.plot(classification_history.history["loss"], label="Training Loss")
plt.plot(classification_history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Binary Crossentropy Loss")
plt.title("Classification Loss Over Time")
plt.legend()
plt.show()

plt.figure(figsize=(7, 5))
plt.plot(classification_history.history["accuracy"], label="Training Accuracy")
plt.plot(classification_history.history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Classification Accuracy Over Time")
plt.legend()
plt.show()

# Classification Predictions
# ============================================================

sample_customers = np.array([
    [45, 0, 60],    # low bill, no issues, long-time customer
    [125, 5, 4],    # high bill, many issues, newer customer
    [90, 2, 24],    # middle case
])

sample_customers_scaled = classification_scaler.transform(sample_customers)

predicted_churn_probabilities = classification_model.predict(sample_customers_scaled)

for customer, probability in zip(sample_customers, predicted_churn_probabilities):
    monthly_bill, support_tickets, months_as_customer = customer
    predicted_class = 1 if probability[0] >= 0.5 else 0

    print(
        f"Customer: ${monthly_bill:.0f}/month, "
        f"{support_tickets:.0f} tickets, "
        f"{months_as_customer:.0f} months "
        f"=> Churn probability: {probability[0]:.2%}, "
        f"Predicted class: {predicted_class}"
    )

# Compare Regression vs Classification
#
# Same general Keras workflow:
#
#   1. Prepare X and y
#   2. Scale X
#   3. Build model
#   4. Compile model
#   5. Train with fit()
#   6. Evaluate
#   7. Predict
#
# Main differences:
#
# REGRESSION
#   Example target:
#       price
#   Output layer:
#       Dense(1)
#   Loss:
#       mse
#   Metric:
#       mae
#   Prediction:
#       a numeric value
#
# CLASSIFICATION
#   Example target:
#       churned or not churned
#   Output layer:
#       Dense(1, activation="sigmoid")
#   Loss:
#       binary_crossentropy
#   Metric:
#       accuracy
#   Prediction:
#       probability / class label
#