# -*- coding: utf-8 -*-
"""FeatureEngineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnZrwzwkfr1jyIGR5JkkB62GCTvyhmCg
"""

"""
Feature Engineering

There are a lot of imports for this but we've seen a good chunk previously
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
# ColumnTransformer allows us to transform our columns
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)

from sklearn.inspection import permutation_importance

RANDOM_STATE=42
np.random.seed(RANDOM_STATE)

"""

Create a messy dataset

We want to practice working with a dataset that has numeric, categorical, missing
and outlier values, normally you'd grab a CSV and work with it like we're doing
here but building it ourselves gives us a little control
"""

def make_churn_data(n=900, random_state=42):
  # Set rng for generating distributions
  rng = np.random.default_rng(random_state)

  # Generate some columns using various distributions
  age = rng.normal(38, 12, n).round().clip(18,80)
  account_age_months = rng.gamma(4, 8, n).round().clip(1, 120)
  monthly_spend = rng.normal(75, 25, n).clip(10, 250)
  support_tickets = rng.poisson(1.6, n)
  days_since_login = rng.exponential(9, n).round().clip(0,90)
  has_discount = rng.choice(["yes", "no"], size = n, p=[.35, .65])
  contract_type = rng.choice(["month-to-month", "one-year", "two-year"], size = n, p=[.55, .3, .15])
  region = rng.choice(['Northeast', 'Southeast', 'Midwest', 'West'], size = n)

  # Build our Logit
  # Think of this as the linear regression before going into the sigmoid function
  logit = (
      -1.1
      + .035 * (monthly_spend - 75)
      + .32 * support_tickets
      + .04 * days_since_login
      -.018 * account_age_months
      + np.where(contract_type == "month-to-month", .9, 0)
      + np.where(contract_type == "two-year", -.7, 0)
      + np.where(has_discount == "yes", -.35, 0)
  )

  # Sigmoid
  prob = 1 / (1 + np.exp(-logit))
  churned = rng.binomial(1, prob)

  df = pd.DataFrame({
      "age": age,
      "account_age_months": account_age_months,
      "monthly_spend": monthly_spend.round(2),
      "support_tickets": support_tickets,
      "days_since_login": days_since_login,
      "has_discount": has_discount,
      "contract_type": contract_type,
      "region": region,
      "churned": churned
  })

  # Inject some missing values
  for col in ["age", "monthly_spend", "contract_type", "region"]:
    missing_idx = rng.choice(df.index, size=int(.06 * n), replace=False)
    df.loc[missing_idx, col] = np.nan

  # Inject some outliers
  outlier_idx = rng.choice(df.index, size = 8, replace=False)
  df.loc[outlier_idx, "monthly_spend"] = rng.choice([450, 500, 650], size = len(outlier_idx))

  return df

df = make_churn_data()
df.head()

"""
Inspect our messy data
We want to see distributions, how many missing values, etc
This is a good first step when preprocessing data you've never seen before
"""

print(df.shape)
print("Distribution")
print(df["churned"].value_counts(normalize=True).round(3))

print("Missing Values")
print(df.isna().sum())

print("Numeric Summary")
df.describe()

"""
At this point we have identified there are some columns with missing values
Some columns with outliers
So what do we do?
"""

# Let's split our data to prevent any data leakage
X = df.drop(columns="churned")
y = df["churned"]

# It's also going to be useful to have our list of numeric versus categorical feature
numeric_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features = X.select_dtypes(include=["object"]).columns.tolist()

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size = .2,
    random_state = RANDOM_STATE,
    stratify=y
)

print(X_train.shape, X_test.shape)

"""
This step here is finally our feature engineering
This is not a step we only do at the beginning we can loop back to this after
making an initial model but we have a couple of goals

Numeric -> Fill missing values with the median -> Scale
Categorical -> Fill missing values with the most frequent -> Encode categories
"""

# Pipelines will change the data as they pass through
numeric_pipeline = Pipeline(steps = [
    # Fill our missing values with the median, we use an Imputer
    ("imputer", SimpleImputer(strategy="median")),
    # Scale the values to help our models that struggle with scale
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline(steps =[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    # How do we encode our categories?
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

# ColumnTransformer which will use the pipelines
preprocessor = ColumnTransformer(transformers = [
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

"""
We'll make 2 models
- Logistic Regression
- Random Forest (Collection of Decision Trees)
"""

# Logistic regression
log_reg_model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
    # More not-churn -> Class has slightly less value
    # Less churned -> class has slightly larger value
])

rf_model=Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(
        n_estimators=200,
        random_state=RANDOM_STATE,
        class_weight="balanced",
        max_depth=8
    ))
])

log_reg_model.fit(X_train, y_train)
rf_model.fit(X_train, y_train)

"""
Evaluation
Evaluation comes after training, we've seen this before where we look at various
metrics like accuracy, precision, recall f1-score, MSE, MAE

"""
print("Logistic Regression")
log_preds = log_reg_model.predict(X_test)
print(classification_report(y_test, log_preds, zero_division=0))

print("Random Forest")
rf_preds = rf_model.predict(X_test)
print(classification_report(y_test, rf_preds, zero_division=0))

log_cm = confusion_matrix(y_test, log_preds)
disp = ConfusionMatrixDisplay(log_cm, display_labels=["Stayed", "Churned"])
disp.plot()
plt.show()

rf_cm = confusion_matrix(y_test, rf_preds)
disp = ConfusionMatrixDisplay(rf_cm, display_labels=["Stayed", "Churned"])
disp.plot()
plt.show()

"""
Cross Validation

So we haven't done this before but it will allow us to see how our model preforms with
different validation splits
"""

models = {
    "Logistic Regression": log_reg_model,
    "Random Forest": rf_model,
}

for name, model in models.items():
    scores = cross_val_score(model, X_train, y_train, cv=5, scoring="f1")
    print(name)
    print("F1 scores:", np.round(scores, 3))
    print("Mean F1:", scores.mean().round(3))
    print("Std:", scores.std().round(3))
    print()

"""
Feature Importance

We've talked about the idea of dropping off features that are potentially less
important (Like an ID field should not affect a regression outcome). How do we
determine when to drop something off? Domain Knowledge is super important here

But if you lack the domain knowledge, there are ways to get ideas about dropping
off data
"""

# With Logistic regression, you can inspect the coefficents after preprocessing and training
# We can look to see which variables contribute the most to churn or not

log_reg_model.fit(X_train, y_train)
feature_names = log_reg_model.named_steps["preprocessor"].get_feature_names_out()
coefs = log_reg_model.named_steps["model"].coef_[0]

coef_df = pd.DataFrame({
    "feature": feature_names,
    "coefficient": coefs,
    "abs_coefficient": np.abs(coefs),
}).sort_values("abs_coefficient", ascending=False)

coef_df.head(15)

"""
Permutation Importance

This basically looks at the order of features and determines if they're important

We'll try training with a couple of different permutations and get a score for how important
a feature is
"""

perm = permutation_importance(
    rf_model,
    X_test,
    y_test,
    n_repeats=5, # Five different ordered
    random_state=RANDOM_STATE,
    scoring="f1"
)

perm_df = pd.DataFrame({
    "feature": X_test.columns,
    "importance_mean": perm.importances_mean,
    "importance_std": perm.importances_std,
}).sort_values("importance_mean", ascending=False)

perm_df