# -*- coding: utf-8 -*-
"""SQLVectorSimilarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKJHnco4wtaQ8aZyEFwc9b4aPUWnLLbG
"""

"""
Vector DBs
Vector DBs are used to store high-dimensional vectors and compare them to do
things like semantic (meaning) search as opposed to just keyword search

Today we'll be implementing this manually without a proper vector db

"""

import sqlite3
import json
import numpy as np
import pandas as pd
# This is what I've use to get our embeddings
from sentence_transformers import SentenceTransformer

"""
Manual Cosine Similarity Function

As a reminder Cosine similarity checks the angle between vectors and returns
a value between -1 and 1 describing how "similar" they are
-1 being complete opposites
1 being the same

"""
def cosine_similarity(a, b):
  a = np.array(a, dtype=float)
  b = np.array(b, dtype=float)
  # We need to get the product of the vector norms
  denominator = np.linalg.norm(a) * np.linalg.norm(b)

  if denominator == 0.0:
    return 0.0

  return float(np.dot(a,b) / denominator)

query_vector = [1, 1]

examples ={
    "very similar": [.9, 1.1],
    "somewhat similar": [1, 0],
    "opposite": [-1, -1]
}

for label, vect in examples.items():
  print(label, cosine_similarity(query_vector, vect))

"""
Now that we can calculate how similar two vectors are, let's create
some "documents' that we can search through with semantic search

Vector DBs typically include the following columns:
id or document name
metadata (to gather info about the document or use it to help filter our results)
text
vector embedding
"""

documents = [
    {"id": "doc-001", "topic": "tensorflow", "text": "CNNs are useful for image classification tasks"},
    {"id": "doc-002", "topic": "tensorflow", "text": "Convolutional neural networks work well when analyzing pictures."},
    {"id": "doc-003", "topic": "ml", "text": "Cross-validation helps estimate how well a model generalizes."},
    {"id": "doc-004", "topic": "ml", "text": "Precision and recall are useful metrics for imbalanced classification."},
    {"id": "doc-005", "topic": "vectordb", "text": "Vector databases store embeddings for similarity search."},
    {"id": "doc-006", "topic": "vectordb", "text": "Chroma can run locally and store documents with metadata."},
    {"id": "doc-007", "topic": "aws", "text": "SageMaker is used to train and deploy machine learning models on AWS."},
    {"id": "doc-008", "topic": "langchain", "text": "RAG retrieves relevant context before sending a prompt to a language model."},
]

df = pd.DataFrame(documents)
df

"""
At this point we have all of our texts, we need to generate our embeddings
We could create a whole network for this but I'm going to use an existing model
"""

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
# This is a sentence model that take a sentence, tokenizes, embeds and pools our sentence
# in a 384-dimension vector

texts = df["text"].tolist()
embeddings = model.encode(texts, normalize_embeddings=True)

print("Number of Documents:", len(embeddings))
print("Embedding Dimension:", len(embeddings[0]))

"""
Try this with a SQL table

Let's load all of this into our SQL table and go from there
"""

# Connection
conn = sqlite3.connect(":memory:") # Only exists in memory, will be deleted if rerun
# Cursor
cur = conn.cursor()

# Execute the Queries

# Create a table
cur.execute("""
CREATE TABLE documents(
  id TEXT PRIMARY KEY,
  topic TEXT,
  text TEXT,
  embedding_json TEXT
)
""")

# Let's add in our rows and embeddings
for row, embedding in zip(documents, embeddings):
  cur.execute(
      "INSERT INTO documents VALUES (?,?,?,?)",
      (row["id"], row["topic"], row["text"], json.dumps(embedding.tolist()))
  )

conn.commit()

pd.read_sql_query("SELECT * FROM documents", conn)

"""

Manual Vector Search (Keyword Search)

Why is using SQL for this not the preferred option? Well in SQL you can
only really do keyword search before the vector similarities so its a little
more difficult

"""

keyword = "pictures"

pd.read_sql_query(
    "SELECT id, topic, text FROM documents WHERE text LIKE ?",
    conn,
    params=(f"%{keyword}%",)
)

"""
Define a new function for searching with vectors
"""
def sqlite_vector_search(query, top_k = 3, topic_filter=None):
  # Get an embedding of the query vector
  query_embedding = model.encode([query], normalize_embeddings=True)[0]

  # Search in a specific topic or else search all
  if topic_filter:
    rows = cur.execute(
        "SELECT * FROM documents WHERE topic = ?",
        (topic_filter, )
    ).fetchall()
  else:
    rows = cur.execute(
        "SELECT * FROM documents"
    ).fetchall()

  scored = []
  for doc_id, topic, text, embedding_json in rows:
    doc_embedding = np.array(json.loads(embedding_json))
    score = cosine_similarity(query_embedding, doc_embedding)

    scored.append({
        "id": doc_id,
        "topic": topic,
        "text": text,
        "score": score
    })

  return pd.DataFrame(scored).sort_values("score", ascending=False).head(top_k)

sqlite_vector_search("pictures")

sqlite_vector_search("What neural network should I use for pictures?")

sqlite_vector_search("How can I evaluate a classification model?")

sqlite_vector_search("How do I search by meaning?", topic_filter="vectordb")
# Using metadata to filter the documents you're looking through

sqlite_vector_search("How can I deploy a machine learning model?")

