# -*- coding: utf-8 -*-
"""CNNs_CIFAR-10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FbWM4hLbTjy_PEcLt4TY2JVDenvkiZLQ
"""

"""
Classifying "Real-Life" images with a CNN
We'll use the CIFAR-10 dataset for images

Goals
Loading the CIFAR-10 DB
Preprocessing and Augmenting the data
Build our CNN
Train and Evaluate
Build a second CNN for improved
"""

import random
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay, classification_report
from fastai.data.external import untar_data, URLs

SEED=42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

"""
Loading CIFAR-10

Yesterday we used the MNIST database for classifying digits
Recall, the data from yesterday was loaded directly from tensorflow
and had a shape of 28x28x1 (28x28 image with 1 color channel)

CIFAR-10 is an image database including 60,000 images spread across 10 classes
The images in CIFAR 10 are 32x32 and in full color so our final shape will be 32x32x3 for each image
Reminder we could pull this from tensorflow but it's sometimes slow
"""

# CIFAR-10 class names
class_names = [
    "airplane", "automobile", "bird", 'cat', 'deer', 'dog',
    'frog', 'horse', 'ship', 'truck'
]

print("Downloading data")
path = Path(untar_data(URLs.CIFAR))

train_dir = path / "train"
test_dir = path / "test"

print("Dataset Path:", path)
print("Train Path:", train_dir)
print("Test Path:", test_dir)

"""
This step is loading them into a Tensorflow dataset
If we loaded this from TF we could skip this step but sometimes you have to do this

Take our images directories and convert them
IMPORTANT:
- class-names to force the integer labels to match our expected order
- shuffle=False keeps the order to properly assign labels
- batch_size this allows us to grab all of the data at once basically

"""
train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    labels="inferred",
    label_mode="int",
    class_names=class_names,
    color_mode='rgb',
    image_size=(32,32),
    batch_size=50000,
    shuffle=False
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    labels="inferred",
    label_mode="int",
    class_names=class_names,
    color_mode='rgb',
    image_size=(32,32),
    batch_size=10000,
    shuffle=False
)

# Convert our DS to NumpyArrays
for images, labels in train_ds.take(1):
  X_train = images.numpy().astype("uint8") # 0-255
  y_train = labels.numpy().astype("int64")

for images, labels in test_ds.take(1):
  X_test = images.numpy().astype("uint8") # 0-255
  y_test = labels.numpy().astype("int64")


print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)
print("y_test shape:", y_test.shape)

"""
Other things to look for when loading data from external sources
Sometimes the data is grouped by class
If I say validation_split=.1 inside the model.fit it'll just take the last 10%
and use it as the validation set

Let's take a look to see if the data is already shuffled
"""

print("First 20 labels:", y_train[:20]) # All airplane
print("Last 20 Labels:", y_train[-20:]) # All Truck

print("Class count in full training set")
for i, name in enumerate(class_names):
  print(f"{name}: {np.sum(y_train == i)}")

# Imagine we used the data as is
# The last 10% would be our validation set
print("Class count in last 10%")
last_10_percent = y_train[-5000:]
for i, name in enumerate(class_names):
  print(f"{name}: {np.sum(last_10_percent == i)}")

# Split this data into train and test splits as we have done, specifically we
# will stratify the data to roughly spread it out

X_train_model, X_val, y_train_model, y_val = train_test_split(
    X_train,
    y_train,
    test_size=.1,
    random_state=SEED,
    stratify=y_train
)

print("Class count in training set")
for i, name in enumerate(class_names):
  print(f"{name}: {np.sum(y_train_model == i)}")

print("Class count in validation set")
for i, name in enumerate(class_names):
  print(f"{name}: {np.sum(y_val == i)}")

"""
Let's look at the data to get a feel
"""

plt.figure(figsize=(10,5))
random_indices = np.random.choice(len(X_train_model), size=20, replace=False)

for plot_position, idx in enumerate(random_indices, start=1):
  plt.subplot(4,5, plot_position)
  plt.imshow(X_train_model[idx])
  plt.title(class_names[y_train_model[idx]])
  plt.axis("off")

plt.show()

"""
Last step for preprocessing (I promise)

Data Augmentation
Data Augementation or modification allows us to artificially create more data
for our training model by augmenting the existing data

Common augments:
Rotate, slide, flip, zoom

"""
# We'll put this inside our model to train later
data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomTranslation(.08, .08),
    tf.keras.layers.RandomZoom(.08)
], name= "data_augmentation")

sample = X_train_model[1764]
label = y_train_model[1764]
print(label)
print(class_names[label])

plt.figure(figsize=(7,4))
for i in range(8):
  # The expand dims turns the shape from (32,32,3) -> (1,32,32,3)
  # Training = true because data augementation is a training tool, it only works
  # when training is set to true (training is true on model.fit())
  augmented = data_augmentation(tf.expand_dims(sample, axis = 0), training=True)
  plt.subplot(2,4, i+1)
  plt.imshow(tf.cast(augmented[0], tf.uint8))
  plt.axis("off")

plt.show()

"""
Helper functions to clear things up later
"""
def plot_history(history, title):
    # Plot training and validation accuracy/loss for one model.
    plt.figure(figsize=(8, 4))
    plt.plot(history.history["accuracy"], label="training accuracy")
    plt.plot(history.history["val_accuracy"], label="validation accuracy")
    plt.title(f"{title} Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.show()

    plt.figure(figsize=(8, 4))
    plt.plot(history.history["loss"], label="training loss")
    plt.plot(history.history["val_loss"], label="validation loss")
    plt.title(f"{title} Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.legend()
    plt.show()


def evaluate_model(model, x_test, y_test, class_names, title):
    # Evaluate a trained model and return useful results.
    test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
    print(f"{title} test accuracy: {test_acc:.4f}")
    print(f"{title} test loss: {test_loss:.4f}")

    y_prob = model.predict(x_test, verbose=0)
    y_pred = np.argmax(y_prob, axis=1)

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=class_names, zero_division=0))

    cm = confusion_matrix(y_test, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
    fig, ax = plt.subplots(figsize=(10, 10))
    disp.plot(ax=ax, xticks_rotation=45, values_format="d")
    plt.title(f"{title} Confusion Matrix")
    plt.show()

    return {
        "title": title,
        "test_loss": test_loss,
        "test_accuracy": test_acc,
        "y_pred": y_pred
    }


def show_mistakes(x_test, y_test, y_pred, class_names, title, max_images=24):
    # Show examples where the model prediction was wrong.
    mistakes = np.where(y_pred != y_test)[0]
    print(f"{title} mistakes:", len(mistakes))

    if len(mistakes) == 0:
        print("No mistakes to show.")
        return

    selected = mistakes[:max_images]

    plt.figure(figsize=(12, 8))
    for i, idx in enumerate(selected):
        plt.subplot(4, 6, i + 1)
        plt.imshow(x_test[idx])
        plt.title(f"T: {class_names[y_test[idx]]}\nP: {class_names[y_pred[idx]]}")
        plt.axis("off")

    plt.suptitle(title)
    plt.tight_layout()
    plt.show()


def plot_comparison(histories, metric, title):
    # Compare one metric across multiple training histories.
    plt.figure(figsize=(8, 4))
    for name, history in histories.items():
        plt.plot(history.history[metric], label=name)
    plt.title(title)
    plt.xlabel("Epoch")
    plt.ylabel(metric)
    plt.legend()
    plt.show()

"""
Baseline CNN

Architecture
Input
Data Augmentation
Rescaling (Why rescale here?)
Convolution Layers
Max Pooling Layers
A Dense Layer (Fully Connected)
Dropout
Softmax output

Why are we rescaling in the model itself? It doesn't really matter too much
but if we can include some of our preprocessing in the model itself
we can use it on more generalized images
"""

baseline_model = tf.keras.Sequential([
    # Input Layer
    tf.keras.layers.Input(shape=(32,32,3)),
    # Augment our data
    # Reminder this implicitly only happens during training
    data_augmentation,
    # Rescaling
    # We can use other scalers here but we know the values are between 0-255
    # so just divide by 255
    tf.keras.layers.Rescaling(1./255),


    # Convolution Blocks
    # Reminder, we add filters to our blocks as pattern learners
    # After learning a pattern we summarize using Pooling
    # Padding
    # Specifically Padding=same allows for the images to not be reduced in size
    tf.keras.layers.Conv2D(32, (3,3), activation="relu", padding="same"), # Learn basic patterns
    tf.keras.layers.Conv2D(32, (3,3), activation="relu", padding="same"), # Learn from the previous output
    tf.keras.layers.MaxPooling2D(), # Summarize the feature maps

    # A lot of this is trial and error
    tf.keras.layers.Conv2D(64, (3,3), activation="relu", padding="same"),
    tf.keras.layers.Conv2D(64, (3,3), activation="relu", padding="same"),
    tf.keras.layers.MaxPooling2D(),

    tf.keras.layers.Conv2D(128, (3,3), activation="relu", padding="same"), # Learn basic patterns
    tf.keras.layers.MaxPooling2D(),


    # Finally we have a representation of the important features in the image
    # So we connect this to an MLP by flattening and then using a dense layer
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(.3),

    #Output
    tf.keras.layers.Dense(10, activation="softmax")
], name="baseline_cnn")

# Compile
baseline_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate= .001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Summarize
baseline_model.summary()

# Let's train the model, we'll define the EarlyStopping callback to prevent overfitting
baseline_callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_accuracy",
        patience=5,
        restore_best_weights=True,
        mode="max" # Checking for Maximized accuracy
    )
]

baseline_history = baseline_model.fit(
    X_train_model,
    y_train_model,
    validation_data=(X_val, y_val),
    epochs=20,
    batch_size=128, # How are the batches determined? Come back to this
    callbacks=baseline_callbacks
)

# Evaluate on our test data
# Uses the helper functions we defined earlier

plot_history(baseline_history, "Baseline CNN")

baseline_results = evaluate_model(
    baseline_model,
    X_test,
    y_test,
    class_names,
    "Baseline CNN"
)

# Let's look at some mistakes to see some misclassifications
show_mistakes(
    X_test,
    y_test,
    baseline_results["y_pred"],
    class_names,
    "Baseline CNN Mistakes"
)

"""

At the point we've built a CNN that classifies images with ~80% accuracy, but we want to try
and pull out as much improvement as we can

- Batch Normalization
  - Batch Normalization is the process of scaling in the middle of a network
  - Rescaling previously was a preprocess step but the actual inputs can increase
  a lot during training so we'll add in BatchNormalization Layers after Conv2D
      - NOTE This removes the need for a bias in those layers
- Adding in More Dropout
- Large Dense Layer
- Larger Convolutional Layer
- Longer Training
- ReduceLROnPlateau
  - As we get closer to a theoretical perfect model, we want to slow down our
  learning rate to prevent overshooting the minimum
"""

improved_model = tf.keras.Sequential([
    # Input Layer
    tf.keras.layers.Input(shape=(32,32,3)),
    # Augment our data
    # Reminder this implicitly only happens during training
    data_augmentation,
    # Rescaling
    # We can use other scalers here but we know the values are between 0-255
    # so just divide by 255
    tf.keras.layers.Rescaling(1./255),


    # Convolution Blocks
    tf.keras.layers.Conv2D(32, (3,3), padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Activation("relu"),
    tf.keras.layers.Conv2D(32, (3,3), padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Activation("relu"),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Dropout(.2),

    tf.keras.layers.Conv2D(64, (3,3), padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Activation("relu"),
    tf.keras.layers.Conv2D(64, (3,3), padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Activation("relu"),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Dropout(.3),

    # Adding in another convolution layer to make this more powerful
    tf.keras.layers.Conv2D(128, (3,3), padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Activation("relu"),
    tf.keras.layers.Conv2D(128, (3,3), padding="same", use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Activation("relu"),
    tf.keras.layers.MaxPooling2D(),
    tf.keras.layers.Dropout(.3),

    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, use_bias=False),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Activation("relu"),
    tf.keras.layers.Dropout(.3),

    #Output
    tf.keras.layers.Dense(10, activation="softmax")
], name="improved_cnn")

# Compile
improved_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=.001),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Summarize
improved_model.summary()

# Training time
improved_callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_accuracy",
        patience=8,
        restore_best_weights=True,
        mode="max" # Checking for Maximized accuracy
    ),
    # Reduce learning rate on Plateau
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=.5,
        patience=3,
        min_lr = 1e-5, #.00001
        verbose = 1
    )
]

improved_history = improved_model.fit(
    X_train_model,
    y_train_model,
    validation_data=(X_val, y_val),
    epochs=40,
    batch_size=128, # How are the batches determined? Come back to this
    callbacks=improved_callbacks
)

plot_history(improved_history, "Improved CNN")

improved_results = evaluate_model(
    improved_model,
    X_test,
    y_test,
    class_names,
    "Improved CNN"
)

show_mistakes(
    X_test,
    y_test,
    improved_results["y_pred"],
    class_names,
    "Improved CNN Mistakes"
)

# Let's compare our test accuracies
print("--- Test Set Comparison ---")
print(f"Baseline CNN accuracy: {baseline_results['test_accuracy']:.4f}")
print(f"Improved CNN accuracy: {improved_results['test_accuracy']:.4f}")
print(f"Accuracy change: {improved_results['test_accuracy'] - baseline_results['test_accuracy']:+.4f}")

print("\nBaseline CNN loss:", round(baseline_results["test_loss"], 4))
print("Improved CNN loss:", round(improved_results["test_loss"], 4))

from google.colab import files
from tensorflow.keras.utils import load_img, img_to_array
import numpy as np
import matplotlib.pyplot as plt

uploaded = files.upload()

image_path = list(uploaded.keys())[0]

img = load_img(
    image_path,
    color_mode="rgb",
    target_size=(32, 32)
)

img_array = img_to_array(img).astype("uint8")
img_batch = np.expand_dims(img_array, axis=0)

predictions = improved_model.predict(img_batch)

predicted_index = np.argmax(predictions[0])
predicted_class = class_names[predicted_index]
confidence = predictions[0][predicted_index]

print("Predicted class:", predicted_class)
print("Confidence:", f"{confidence:.2%}")

print("\nAll class probabilities:")
for class_name, probability in zip(class_names, predictions[0]):
    print(f"{class_name:12s}: {probability:.2%}")

plt.imshow(img_array)
plt.title(f"Prediction: {predicted_class} ({confidence:.2%})")
plt.axis("off")
plt.show()