# -*- coding: utf-8 -*-
"""GraphsAndFunctional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pWUWILOph1BXr00-G49l9ZrsbBiZenta
"""

"""
Getting Started

Graphs and Sessions
A Computational Graph is what TensorFlow uses to optimize your operations so
they can run quickly and in parallel

In the olden days of TensorFlow 1, you'd run a graph in a Session, not necessary now
"""

import os
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import tensorflow as tf

from IPython.display import display, Image
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

np.random.seed(42)
tf.random.set_seed(42)

# Eager Execution
# This is what happens now
# TF behaves like python and completes the operation the second you ask for it

x = tf.constant([[1.0, 2.0], [3.0, 4.0]], name="x")
w = tf.constant([[.5], [1.5]], name="w")
b = tf.constant([.25], name="b")

# Standard activation in a hidden neuron
eager_output = tf.nn.relu(tf.matmul(x, w) + b)

print("Eager Result: \n", eager_output.numpy())

""" You can still create a manual TF graph these days
this is used for custom training flows or steps
but we'll create a simple function that does the same thing as above
"""

# To turn this into a graph we need a decorator on the function
@tf.function
def tiny_graph(x, w, b):
  # Matrix Multiply -> add bias -> ReLU
  z = tf.matmul(x, w, name="matrix_multiply")
  z = tf.add(z, b, name="add_bias")
  return tf.nn.relu(z, name="relu_activation")

# Graph doesn't get made until you call the function the first time
# graph_output = tiny_graph(x, w, b)
# print("Graph result: \n", graph_output.numpy())

# Get our concrete function
concrete_fn = tiny_graph.get_concrete_function(x, w, b)

# This will give us our list of operations
for op in concrete_fn.graph.get_operations():
  print(f"{op.name:35s} | {op.type}")

"""
At this point we want to take a look at the visual component of the graph under
the hood, but we need to tell TF to watch for it before we can put in a log

This is just for visualization, not explicitly necessary
"""

logdir = "logs/tiny_graph"
shutil.rmtree(logdir, ignore_errors=True)

# Create a writer to write the graph itself

writer = tf.summary.create_file_writer(logdir)

with writer.as_default():
  # Turn on the TRACE so TF can view the graph and record it
  tf.summary.trace_on(graph=True, profiler=False)

  # Call the function for the first time
  _ = tiny_graph(x, w, b)

  tf.summary.trace_export(
      name="tiny_graph_trace",
      step=0
  )

writer.close()

# Commented out IPython magic to ensure Python compatibility.
# Let's view the graph using tensorboard
# %load_ext tensorboard
# %tensorboard --logdir logs

# Functional Model
# This is a different way to do custom neural networks with more advanced arch

# Create some fake classification data
X, y = make_classification(
    n_samples=1600,
    n_features = 8,
    n_informative =5,
    n_redundant = 1,
    n_repeated = 0,
    n_classes = 2,
    class_sep = 1.2,
    random_state=42
)

# Preprocess our data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=.2, random_state=42, stratify=y
)

# Scale our data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""
Build a functional model
You'll usually see this in an actual function itself
and the function returns the actual model
"""

def build_functional_model(input_dim: int) -> tf.keras.Model:
  # Input layer
  inputs = tf.keras.Input(shape = (input_dim,), name="customer_features")

  # Main Branch
  main = tf.keras.layers.Dense(32, activation="relu", name="dense_main_1")(inputs)
  main = tf.keras.layers.Dense(16, activation="relu", name="dense_main_2")(main)

  # Skip Branch
  skip = tf.keras.layers.Dense(16, activation="relu", name="skip_projection")(inputs)

  # Merge our branches
  merged = tf.keras.layers.Concatenate(name="merge_branches")([main, skip])
  hidden = tf.keras.layers.Dense(16, activation="relu", name="hidden_after_merge")(merged)
  outputs = tf.keras.layers.Dense(1, activation="sigmoid", name="churn_probability")(hidden)

  # Compile
  model = tf.keras.Model(inputs=inputs, outputs=outputs, name="fictional_churn_model")
  model.compile(
      optimizer = tf.keras.optimizers.Adam(learning_rate=.001),
      loss="binary_crossentropy",
      metrics = ["accuracy"]
  )
  # Return
  return model

model = build_functional_model(X_train.shape[1])
model.summary()

plot_path = "functional_model_graph.png"

try:
    tf.keras.utils.plot_model(
        model,
        to_file=plot_path,
        show_shapes=True,
        show_layer_names=True,
        expand_nested=False,
        dpi=110,
    )
    display(Image(filename=plot_path))
except Exception as exc:
    print("Could not create plot_model image in this runtime.")
    print("Model summary above still shows the graph connections.")
    print("Error:", exc)

logdir = "logs/functional_model"
shutil.rmtree(logdir, ignore_errors=True)

callbacks = [
    tf.keras.callbacks.TensorBoard(log_dir=logdir, write_graph=True),
    tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True),
]

history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=12,
    batch_size=32,
    callbacks=callbacks,
    verbose=1,
)

test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print(f"Test loss: {test_loss:.4f}")
print(f"Test accuracy: {test_acc:.4f}")

save_dir = Path("saved_models")
save_dir.mkdir(exist_ok=True)
keras_path = save_dir / "functional_churn_model.keras"

model.save(keras_path)
print("Saved model to:", keras_path)

loaded_model = tf.keras.models.load_model(keras_path)
print("Loaded model:", loaded_model.name)

original_preds = model.predict(X_test[:5], verbose=0)
loaded_preds = loaded_model.predict(X_test[:5], verbose=0)

comparison = pd.DataFrame({
    "original_prediction": original_preds.ravel(),
    "loaded_prediction": loaded_preds.ravel(),
    "difference": np.abs(original_preds.ravel() - loaded_preds.ravel()),
})

display(comparison)
print("Max prediction difference:", comparison["difference"].max())
print(os.path.getsize(keras_path))