# -*- coding: utf-8 -*-
"""NLP and RNNs Intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17P5qEgEmLAu42tHwzwylihbBgKGTSv3I
"""

"""
Goals:
Learn about NLP
Learn about basic RNNs
Learn about Transformer and some transfer learning

Motivating Example:
Classifying IMDB reviews as positive or negative (sentiment analysis)

What is NLP?
Natural Language Processing -> Ability to read, understand, and generate natural sounding text

"""

!pip install -U protobuf tensorflow-metadata tensorflow-datasets

# Imports
import os
import datetime
import shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_datasets as tfds

from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Setup piece IGNORE FOR LATER
# Clears out old tensorboard stuff, will recap later
RUN_ID = datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
BASE_LOG_DIR = os.path.join("logs", f"imdb_nlp_{RUN_ID}")

if os.path.exists(BASE_LOG_DIR):
  shutil.rmtree(BASE_LOG_DIR)
  # Clears out existing logs for tensorboard

"""
Preprocessing time
Load Data -> Raw Text -> Tokens -> Embeddings -> Model
"""

# Load the data from TensorFlow Datasets
(train_raw, val_raw, test_raw), info = tfds.load(
    "imdb_reviews",
    split=["train[:80%]", "train[80%:]", "test"],
    as_supervised=True, # Gives us the labels for the data
    with_info = True
)

print(info)
print("Original train examples:", info.splits["train"].num_examples)
print("Original test examples:", info.splits["test"].num_examples)

# Let's take a look at some raw data
for text, label in train_raw.take(10):
  print("Label:", int(label.numpy()), "(1 = positive, 0=negative)")
  print(text.numpy().decode("utf-8")[:700])

"""
So now we've seen what the reviews will look like
Let's tokenize them

IMPORTANT: Our model is expecting data of a consistent shape to learn
Some reviews will be too short and some too long
We PAD the short reviews and TRUNCATE the long ones

"this movie was so good"
-> [11, 47, 18, 36, 92, 0, 0, 0, .....]
"""

vectorize_layer = tf.keras.layers.TextVectorization(
    max_tokens = 20000, # Dictionary Size
    output_mode="int",
    output_sequence_length=250, # 250 tokens or words
    standardize="lower_and_strip_punctuation",
    name="text_vectorization"
)

# Similar to what we've done previously, we'll adapt (apply) this to only the
# training data. If new words come up in the validation or test set, they will
# be marked as UNK (unknown)
# Each example has both text and a label so strip and adapt
train_text_only = train_raw.map(lambda text, label: text) # Just return the text
vectorize_layer.adapt(train_text_only.batch(128))
# Why are we batching here?
# This prevents the entire dataset from being loaded into our RAM at once
# We could probably handle it (20,000 sample right now)
# But as out datasets get bigger that would slow things down dramatically

# After adapt() we can then inspect the learned vocabulary
vocab = vectorize_layer.get_vocabulary()
VOCAB_SIZE = len(vocab)

print("Vocab Size:", VOCAB_SIZE)
print("First 20 vocab entries")
print(vocab[:20])

# Let's look at the token vectorization of a sample would be
for text,label in train_raw.take(1):
  sample_text = text.numpy().decode("utf-8")
  vectorized = vectorize_layer(tf.constant([sample_text]))

  print("Original Text:")
  print(sample_text[:700]) # Prints the first 700 character
  print("First 40 token ids")
  print(vectorized.numpy()[0][:40])
  print("First 40 token ids decoded")
  print([vocab[token_id] for token_id in vectorized.numpy()[0][:40]])

# Shuffle our training dataset and we will batch all of our datasets

# What is this? It depends on where it's used but for preprocessing it basically
# allows us to load the next batch while the current batch is running
# to prevent any delays
AUTOTUNE = tf.data.AUTOTUNE

def prepare_datasets(ds, batch_size=128, shuffle=False):
  if shuffle:
    ds = ds.shuffle(10000, seed=42, reshuffle_each_iteration=True)
  return ds.batch(batch_size).prefetch(AUTOTUNE)

train_ds = prepare_datasets(train_raw, shuffle=True)
val_ds = prepare_datasets(val_raw)
test_ds = prepare_datasets(test_raw)

def make_callbacks(model_name, patience=2):
    log_dir = os.path.join(BASE_LOG_DIR, model_name)

    return [
        tf.keras.callbacks.TensorBoard(
            log_dir=log_dir,
            histogram_freq=0,
        ),
        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=patience,
            restore_best_weights=True,
        ),
        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=1,
            min_lr=1e-6,
            verbose=1,
        ),
    ]


def plot_history(history, title):
    history_df = pd.DataFrame(history.history)

    if "loss" in history_df and "val_loss" in history_df:
        plt.figure()
        plt.plot(history_df["loss"], label="train_loss")
        plt.plot(history_df["val_loss"], label="val_loss")
        plt.title(f"{title}: Loss")
        plt.xlabel("Epoch")
        plt.ylabel("Loss")
        plt.legend()
        plt.show()

    if "accuracy" in history_df and "val_accuracy" in history_df:
        plt.figure()
        plt.plot(history_df["accuracy"], label="train_accuracy")
        plt.plot(history_df["val_accuracy"], label="val_accuracy")
        plt.title(f"{title}: Accuracy")
        plt.xlabel("Epoch")
        plt.ylabel("Accuracy")
        plt.legend()
        plt.show()


def get_true_labels(dataset):
    return np.concatenate([labels.numpy() for _, labels in dataset], axis=0)


def evaluate_binary_sigmoid_model(model, dataset, model_name):
    y_true = get_true_labels(dataset)
    y_prob = model.predict(dataset, verbose=1).ravel()
    y_pred = (y_prob >= 0.5).astype("int32")

    print(f"\n{model_name} classification report:")
    print(classification_report(y_true, y_pred, target_names=["negative", "positive"]))

    cm = confusion_matrix(y_true, y_pred)
    disp = ConfusionMatrixDisplay(cm, display_labels=["negative", "positive"])
    disp.plot(values_format="d")
    plt.title(f"{model_name}: Confusion Matrix")
    plt.show()

    return {
        "model": model_name,
        "accuracy": np.mean(y_true == y_pred),
        "confusion_matrix": cm,
    }


def evaluate_logits_model(model, dataset, model_name):
    y_true = get_true_labels(dataset)
    logits = model.predict(dataset, verbose=1)
    y_pred = np.argmax(logits, axis=1)

    print(f"\n{model_name} classification report:")
    print(classification_report(y_true, y_pred, target_names=["negative", "positive"]))

    cm = confusion_matrix(y_true, y_pred)
    disp = ConfusionMatrixDisplay(cm, display_labels=["negative", "positive"])
    disp.plot(values_format="d")
    plt.title(f"{model_name}: Confusion Matrix")
    plt.show()

    return {
        "model": model_name,
        "accuracy": np.mean(y_true == y_pred),
        "confusion_matrix": cm,
    }

"""
Let's take our first shot at an NLP model
Basic Archtitecture
Input -> Tokenize -> Embeddings -> Pool -> MLP -> Output

Why are we pooling? Pooling is like a summary
Our first attempt will basically be doing a summary of the words present
If we have more positive words, it will be classified as positive
"""

pooling_model = tf.keras.Sequential([
    # Input Layer
    tf.keras.layers.Input(shape=(), dtype=tf.string, name="review_text"),

    # Tokenize (Vectorize)
    # Defines the shape to be those 250 token values
    vectorize_layer,

    # Embedding Step
    # This is where our model learns the relationships between words
    # Our model will learn parameters and group related words together within the
    # vector space
    # Good and great should have similar values
    tf.keras.layers.Embedding(
        input_dim = VOCAB_SIZE,
        output_dim = 64, # Number of relationships learned for each token
        mask_zero = True, # This tells the model to basically ignore the padding
        name="token_embedding"
    ),

    # At this point the model can change depending on if you're using a RNN or not
    # In this case we are not

    # Pool or summarize each column of embedded values
    # How many positive or negative words are there
    tf.keras.layers.GlobalAveragePooling1D(name="average_token_embeddings"),

    # Connect this to an MLP
    tf.keras.layers.Dense(32, activation="relu"),
    tf.keras.layers.Dropout(.3),

    # Output
    # Probability the review is positive (or labelled as 1)
    tf.keras.layers.Dense(1, activation="sigmoid", name="sentiment")
])

# Compile
pooling_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=.001),
    loss="binary_crossentropy",
    metrics = [
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

pooling_model.summary()

history_pooling = pooling_model.fit(
    train_ds,
    validation_data = val_ds,
    epochs = 6,
    callbacks = make_callbacks("01_embedding_pooling_baseline")
);

# Plot our data to track
plot_history(history_pooling, "Embedding + Pooling Baseline")

pooling_results = evaluate_binary_sigmoid_model(
    pooling_model,
    test_ds,
    "Embedding + Pooling Baseline"
)

"""
Why might this model not be the most accurate?

Some issues:
"I thought the movie was going to be terrible but it turned out to be good" -> 0
"The movie was not bad at all" -> 0 when it should be a 1

We basically need information from the context of the words themselves
not + bad -> good
not (neutral) + bad (negative) would average to bad but put together it's good

Idea of the Recurrent Neural Network
Basically we loop in the same layer (recurring) and develop memory for what came before

Types:
RNNs - Old school way of doing NLPs, generally suffered on longer inputs
GRUs -> Gated Recurrent Unit
LSTM -> Long Short-Term Memory
  - Both GRUs and LSTMs use "gates" to keep track of important features as well
  as what to remember and what to forget. LSTMs are more complex so they can handle
  more things and GRUs are simpler so they're easier to practice
RNNs of any type are good for things where the SEQUENCE matters (text, time-series)

Modern NLP uses a Transformer (we'll talk about transformers later) but they use
a little bit of a different technique, they let tokens look at each other directly

"""

gru_model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(), dtype=tf.string, name="review_text"),

    # Tokenize (Vectorize)
    # Defines the shape to be those 250 token values
    vectorize_layer,

    # Embedding Step
    tf.keras.layers.Embedding(
        input_dim = VOCAB_SIZE,
        output_dim = 64, # Number of relationships learned for each token
        mask_zero = True, # This tells the model to basically ignore the padding
        name="token_embedding"
    ),

    # At this step we'll add in  2 things
    # Spatial Dropout
    # Special kind of dropout layer, instead of dropping one value it'll drop a vector
    tf.keras.layers.SpatialDropout1D(.2),

    # Bidirectional GRU
    # We are dependent on info that comes both before and after
    tf.keras.layers.Bidirectional(
        tf.keras.layers.GRU(64, dropout=.25),
        name="bidirectional_gru"
    ),

    # MLP
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dropout(.4),
    # Output layer
    tf.keras.layers.Dense(1, activation="sigmoid", name="sentiment")
])

gru_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=.001),
    loss="binary_crossentropy",
    metrics = [
        "accuracy",
        tf.keras.metrics.Precision(name="precision"),
        tf.keras.metrics.Recall(name="recall")
    ]
)

gru_model.summary()

history_gru = gru_model.fit(
    train_ds,
    validation_data = val_ds,
    epochs = 8,
    callbacks = make_callbacks("O2_bidirectional_gru", patience=3)
)

plot_history(history_gru, "Bidirectional GRU")
gru_results = evaluate_binary_sigmoid_model(
    gru_model,
    test_ds,
    "Bidirectional GRU"
)

# Commented out IPython magic to ensure Python compatibility.
"""
TensorBoard
TensorBoard is a tool used to visualize all the graphs and things I write using
a built in tool with a nice GUI

We store our information in a log file through our callback functions and then
can view all of the data as needed
"""
# %load_ext tensorboard
# %tensorboard --logdir logs